# GitHub Windows VMs don't have WSL2 installed. Tests won't work there.
# We just run static type checking.
name: Test

on: [push]

jobs:
  test:
    runs-on: windows-latest
    # strategy:
    #  matrix:
    #    python-version: [3.7, 3.8, 3.9]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          #   python-version: ${{ matrix.python-version }}
          python-version: 3.7
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.1.0
      - name: Install dependencies
        run: poetry install
      - name: Type checking
        run: poetry run mypy src/wsl_tools
#      - name: Test with pytest
#        run: poetry run pytest --cov=./ --cov-report=xml
#      - name: Upload coverage to Codecov
#        uses: codecov/codecov-action@v1
#        with:
#          file: ./coverage.xml
#          verbose: true
